# 应用名称
spring:
  application:
  name: SpringDataJPADemo
  datasource:
    url: jdbc:mysql://localhost:3306/student?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 1249
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update
    # 控制台显示SQL
    show-sql: true
  # 应用服务 WEB 访问端口
server:
  port: 8081

